CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) default charset utf8 COMMENT '';

CREATE TABLE IF NOT EXISTS cults(
  id INT PRIMARY KEY COMMENT 'PRIMARY CULT ID KEY',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'WHEN CULT WAS CREATED',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'WHEN CULT WAS LAST UPDATED',
  name VARCHAR(75) NOT NULL COMMENT 'CULT NAME',
  fee INT DEFAULT 0 COMMENT 'FEE TO GET INTO CULT',
  description VARCHAR(500) NOT NULL COMMENT 'DESCRIPTION OF THE CULT',
  coverImg VARCHAR(500) NOT NULL COMMENT "COVER IMAGE OF CULT",
  leaderId VARCHAR(255) NOT NULL 'LEADER ID "CREATOR ID"',
  Foreign Key (leaderId) REFERENCES accounts(id)
) default charset utf8 COMMENT ''; 

CREATE TABLE IF NOT EXISTS cultMembers (
  id INT PRIMARY KEY COMMENT 'PRIMARY CULT MEMBER ID',
  cultId INT NOT NULL,
  accountId VARCHAR(255) NOT NULL,
  Foreign Key (cultId) REFERENCES cults(id),
  Foreign Key (accountId) REFERENCES accounts(id)
) default charset utf8 COMMENT '';